//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub column_id: i32,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub position: i32,
    pub priority: Option<String>,
    pub due_date: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::column::Entity",
        from = "Column::ColumnId",
        to = "super::column::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Column,
}

impl Related<super::column::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Column.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
